---
- hosts: localhost
  gather_facts: false
  collections:
  - netapp.ontap
  vars:
    hostname: NTAPCL01
    vserver: svm_data
    src_aggr: aggr_data_N1    
    dst_aggr: aggr_vlt_N1
    src_cluster: NTAPCL01
    dst_cluster: NTAPVLT01
    kpath: /etc/ssl/private/ansissluser.key
    fpath: /etc/ssl/private/ansissluser.crt
    validate_certs: false  

  vars_prompt:
    - name: src_vserver
      prompt: Type in source SVM name?
      private: no

    - name: src_volume
      prompt: Type in source volume name?
      private: no

    - name: dst_vserver
      prompt: Type in destination vserver name?
      private: no

    - name: dst_volume
      prompt: Type in destination volume name?
      private: no
        
  tasks:
  - name: Break Snapmirror
    na_ontap_snapmirror:
      state: present
      source_volume: "{{ src_volume }}"
      destination_volume: "{{ dst_volume }}"
      source_vserver: "{{ src_vserver }}"
      destination_vserver: "{{ dst_vserver }}"
      relationship_state: broken
      hostname: "{{ dst_cluster }}"
      key_filepath: "{{ kpath }}"
      cert_filepath: "{{ fpath }}"  
      validate_certs: false
  - name: Create Reverse SnapMirror
    na_ontap_snapmirror:
      state: present
      source_volume: "{{ dst_volume }}"
      destination_volume: "{{ src_volume }}"
      source_vserver: "{{ dst_vserver }}"
      destination_vserver: "{{ src_vserver }}"
      schedule: hourly
      policy: MirrorAllSnapshots
      initialize: False
      hostname: "{{ src_cluster }}"
      key_filepath: "{{ kpath }}"
      cert_filepath: "{{ fpath }}"  
      validate_certs: false
  - name: Resync
    na_ontap_snapmirror:
      state: present
      source_volume: "{{ dst_volume }}"
      destination_volume: "{{ src_volume }}"
      source_vserver: "{{ dst_vserver }}"
      destination_vserver: "{{ src_vserver }}"
      relationship_state: active
      initialize: False
      hostname: "{{ src_cluster }}"
      key_filepath: "{{ kpath }}"
      cert_filepath: "{{ fpath }}"  
      validate_certs: false
  - name: Delete the old snapmirror
    na_ontap_snapmirror:
      state: absent
      source_hostname: "{{ src_cluster }}"
      source_volume: "{{ src_volume }}"
      destination_volume: "{{ dst_volume }}"
      source_vserver: "{{ src_vserver }}"
      destination_vserver: "{{ dst_vserver }}"
      relationship_info_only: true
      hostname: "{{ dst_cluster }}"
      key_filepath: "{{ kpath }}"
      cert_filepath: "{{ fpath }}"  
      validate_certs: false

